/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116796-gb730defd52-20240830"
#endif /* AVUTIL_FFVERSION_H */
