/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116843-gae9cf903e8-20240903"
#endif /* AVUTIL_FFVERSION_H */
